%global tl_name elpres
%global tl_revision 76790

Name:		texlive-%{tl_name}
Epoch:		1
Version:	1.1
Release:	%{tl_revision}.1
Summary:	A simple class for electronic presentations
Group:		Publishing
URL:		https://www.ctan.org/tex-archive/macros/latex/contrib/elpres
License:	lppl
Source0:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/elpres.r%{tl_revision}.tar.xz
Source1:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/elpres.doc.r%{tl_revision}.tar.xz
BuildArch:	noarch
BuildSystem:	texlive
BuildRequires:	texlive-tlpkg
%texlive_base_requires
Provides:	texlive(%{tl_name}) = %{tl_revision}

%description
The elpres class is intended to be used for presentations on a screen or
with a beamer/projector. It is derived from LaTeX's article class and
can be used with LaTeX, pdfLaTeX, and LuaLaTeX. The default "virtual
paper size" of presentations generated by this class corresponds to a
4:3 (width:height) aspect ratio. Other aspect ratios for widescreen
monitors (16:9, 16:10) may be selected.

